### ISSUE TITLE
Capture Sent Messages

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#1]
### DESCRIPTION
Sent messages are not synced to the server. Do we want them to be?

### STEPS
1. Send a message.
2. Sync to server.
3. The message does not appear.

### EXPECTED
First we need to decide whether we want the sent messages to be synced. If so, the desired behavior is clear.

### OBSERVATIONS
Currently no messages originating from the user of the app are stored in the database.

**Comment by fahadp** [comment]
Fixed with ["Sent messages are being recorded now and it syncs to the server"](https://github.com/uw-ictd/dfs-phishing-sms-client/commit/dd29c58b703a4568fd7fb107f786e50e65f81a6f) commit.
