### ISSUE TITLE
Tags for App UI and Database are not consistent

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#12]
### DESCRIPTION
A message may be tagged in the database, but the tag is not appearing in the app.

### STEPS
1. Tag a conversation.
2. Sync data.
3. Refresh view.

### EXPECTED
The tag should be displayed in the UI.

### OBSERVATIONS
The tag appears correctly in the server database but does not display in the app UI. I'm not sure whether the tag is stored in Android database.

**Comment by seanjaffe1** [comment]
We found the cause to be failure in the query and update to use the same format for the address

**Comment by fahadp** [comment]
This issue is probably solved. @stcastle please verify it.

**Comment by sbmare** [comment]
Tested on the gitlab repo. Tags are consistent.
