### ISSUE TITLE
Put "mark as private" and "mark as fraud/spam/etc" in correct contexts

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#13]
### DESCRIPTION
Do we want the menu options for marking the conversations as private or for tagging to appear on the menus in the main app view or the per-conversation thread view? This is separate than the icons appearing in the banner. I'm referring to the menu options.

**Comment by fahadp** [comment]
This issue has been fixed by Sean. The options are inside a conversation view as well as on select of multiple conversations in the main list view.
