### ISSUE TITLE
Privacy tag not updating immediately

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#14]
### DESCRIPTION
Privacy UI indicator does not update unless the display is explicitly refreshed by the user.

### STEPS
1. Mark conversation as private.
2. Wait...
3. No indicator is displayed.
4. Rotate main screen then un-rotate to force the view to update.

### EXPECTED
Changing the privacy status should trigger an event which causes the screen to update automatically.

**Comment by seanjaffe1** [comment]
Just pushed a hack to fix this issue. Should look into a better option.

**Comment by fahadp** [comment]
This has been fixed by Sean.
