### ISSUE TITLE
Wrong conversation view after starting a group message

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#17]
### DESCRIPTION
When creating a group message, after sending the first message, the view jumps to the conversation view with only the first recipient. Message is sent as expected, but the view changes.

### STEPS
1. Have a one-on-one SMS conversation with Person A.
2. Start a new group conversation with Person A and at least one other person. Add Person A as the first recipient.
3. Send a message.

### EXPECTED
The conversation view should jump to the newly created group message.

### OBSERVATIONS
I've seen this a few times, but it needs to be more rigorously reproduced.

**Comment by fahadp** [comment]
I have observed this too, that it jumps to the conversation thread of first recipient in the list.

**Comment by fahadp** [comment]
Hamza supposedly fixed it. I think its right fix but I will have to run it to verify.
