### ISSUE TITLE
Set Private (off) appearing twice in menu

### ISSUE THREAD

**Issue by fahadp** [uw-ictd/dfs-phishing-sms-client#20]
### DESCRIPTION
Set Private (off) is appearing twice in the menu of a conversation thread view.

### STEPS
1. Open the app
2. Select a specific conversation to open it
3. Open menu from top right corner of the app

### EXPECTED
Set Private (off) should appear once.

**Comment by fahadp** [comment]
Hamza fixed it but I think we will face the same problem with other options too. I think we need to discuss it. Here is the comment I left on his fix:

_For sake of consistency, delete R.id.menu_uw_convo_private not R.id.menu_uw_convo_private_text. "_text" means that the option is appearing as text in the menu. Without the _text means that it is aimed to appear as an icon on the top. I believe that mark private is appearing twice because the screen can not take more icons so it pushes it to the menu. **Could you somehow check if it is appearing on the top header or being pushed in the menu?** Because we will have duplication issue for other options too if the screen size is small. Just for context, for each option we have placed it twice (one for icon and one for test in the menu) because we want to have those icons appear on the top for convenient marking but in case some user is novice, we have the option in the menu as text in case user don't remember which icon is for what. Android tries to puts option items with icon field set on the top header of the conversation. If it can't then it pushes it to the side menu as full text.

Sorry for long rambling here._

**Comment by sbmare** [comment]
Patched Hamza's code with your suggested changes.
