### ISSUE TITLE
Cannot tag conversations when viewing the message thread

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#28]
### DESCRIPTION
When you are viewing a single conversation, there is a row of icons on the top bar to tag the message as ok, fraud, spam, etc. These buttons don't do anything from this view.

### STEPS
1. Tap on a conversation.
2. Tap the icons at the top to tag the conversation.
3. Hit the back arrow for main screen, and the conversation is not tagged.

### EXPECTED
The icons should either work or not be there at all.

**Comment by fahadp** [comment]
Humza has the fix in his code that I reviewed and it looks good. We will close this issue once he pushes his changes to this branch.
