### ISSUE TITLE
Toast/pop-up "Cannot tag old conversations" if someone tries to tag a previous conversation.

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#3]
### DESCRIPTION
We decided to not allow users to tag conversations that occurred entirely before installing the app. This is because they are not stored in our database. Users are not able to tag them, but there is no feedback on this.

### STEPS
1. From app home screen, scroll down to find a conversation with no new messages since installing the app.
2. Try to tag the conversation.

### EXPECTED
Display a toast message or pop up to say "Cannot tag old conversations."

### OBSERVATIONS
The tag is not allowed, but currently there is no feedback to the user.

**Comment by seanjaffe1** [comment]
resolved with commit 'popup for untaggable messages added'
