### ISSUE TITLE
Data sync test

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#4]
### DESCRIPTION
We are not confident that all data are properly syncing.

### STEPS
1. Use the app for a while.
2. Check database that all data have synced.

### EXPECTED
All messages sent and received since installing the app should sync. Group messages and MMS should also sync, though this may be a separate issue.

### OBSERVATIONS
We initially suspected that data do not sync until the user has configured MMS. This, however, does not seem to be the case because we saw data sync before MMS.

**Comment by stcastle** [comment]
Also check the labels to make sure that these are syncing correctly.

**Comment by fahadp** [comment]
No formal process done but we have been debugging the app and has not encountered any sync issues.
