### ISSUE TITLE
MMS Sync

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#5]
### DESCRIPTION
MMS messages do not sync.

### STEPS
1. Receive an MMS.
2. Sync data.
3. Check database.

### EXPECTED
Some data about the message should sync to the database.

**Comment by fahadp** [comment]
Fixed. Commit "Add received MMS in sideband DB, add contactbook ID in Android SMS DB…
" File "[NotificationManager](https://github.com/uw-ictd/dfs-phishing-sms-client/commit/f6bd96b25bcd8f9e4a83b2217aa1dc7f74b1e500#diff-ceeab3a0fbbb2d89edf56e53e8312927)".
