### ISSUE TITLE
Delete private data after app re-install

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#8]
### DESCRIPTION
Messages that have been synced to database cannot be deleted if the app is re-installed.

### STEPS
1. Install the app.
2. Receive some message.
2. Sync new conversations to database.
3. Delete app.
5. Re-install app.
6. Mark the conversation as private.
7. Sync to database.

### EXPECTED
All corresponding messages in the database should be deleted when the conversation is marked as private.

### OBSERVATIONS
Instead, the messages will persist in the database if they were present before the app was deleted and re-installed.

**Comment by fahadp** [comment]
Sam's server fix resolved this issue.
