### ISSUE TITLE
Make sure private data is deleted in general

### ISSUE THREAD

**Issue by stcastle** [uw-ictd/dfs-phishing-sms-client#9]
### DESCRIPTION
Data from conversations marked as private seems to disappear, but this needs to be thoroughly tested.

### STEPS
1. Receive a message.
2. Sync the data.
3. Mark as private sometime later.
4. Data should be deleted from server database.

### EXPECTED
Data should not persist on server after conversation is marked as private.

### OBSERVATIONS
This may actually work correctly, but it needs to be tested.

**Comment by fahadp** [comment]
Performed some test and is working.
